global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    environment: Cloud-Portal

remote_write:
  - url: https://enlaces.oceanbyh10.com:9090/api/v1/write
    basic_auth:
      username: admin
      password: leirbag22

scrape_configs:

  - job_name: 'telegraf'
    scrape_interval: 10s
    static_configs:
      - targets:
        - "telegraf:9273"

  - job_name: 'MK'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['189.206.125.252:2161']
        labels:
          service: 'PORTAL-MK'
          sitio: 'OCT'
          proveedornat: 'Alestra'
      - targets: ['186.96.183.196:2161']
        labels:
          service: 'PORTAL-MK'
          sitio: 'OMR'
          proveedornat: 'TotalPlay'
    metrics_path: /snmp
    params:
     module: [MK]
     auth: [passwords-MK]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116
